### ISSUE TITLE
Blank CHANGELOG.md and FAQ.md

### ISSUE THREAD

**Issue by DevinWalker** [ahoereth/gulp-readme-to-markdown#2] opened 2015-03-10 01:54 UTC
Looks like my changelog.md and FAQ.md files aren't being populated correctly. Nothing too crazy going on in my readme. You can see it here: https://github.com/WordImpress/Give/blob/master/readme.txt

**Comment by ahoereth** [comment] 2015-03-11 14:47
Cannot reproduce. Works fine for me with your readme and the settings from the usage example.

**Comment by ahoereth** [comment] 2016-08-30 14:50
Closing this because I did not hear back from OP.

**Closed as completed by ahoereth** 2016-08-30 14:50 UTC
